<a href="https://colab.research.google.com/github/athxrva1/rick-roll1/blob/main/Data_Science_and_ML_YT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import math

def loan_emi(amount : int, duration : int ,rate : float, down_payment = 0) -> float:
    emi = ((amount - down_payment) * rate * ((1+rate)**duration)) / (((1+rate)**duration) - 1)
    return math.ceil(float(str(emi).format()))

In [3]:
emi1 = loan_emi(1.26e6, 8 * 12, 0.1 / 12, 3.0e5)
print(emi1)

14568


In [4]:
emi2 = loan_emi(1.26e6, 10 * 12, 0.08 / 12)
print(emi2)


15288


**Working with numerical data in python**

In [5]:
kanto = [70,62,35]
weights = [0.3, 0.2, 0.4]

In [6]:
def yielder(region, weights):
    result = 0
    for x, w in zip(region, weights): #Makes tuples out of the given values
        result += x * w
    return result

In [7]:
print(yielder(kanto,weights))

47.4


**NUMPY**

In [8]:
import numpy as np
kanto = np.array([70,62,35])
weights = np.array([0.3,0.2,0.4])

In [9]:
print(kanto)
print(weights)
print(type(kanto))

[70 62 35]
[0.3 0.2 0.4]
<class 'numpy.ndarray'>


In [10]:
result = np.dot(kanto, weights)
print(result)

47.4


In [11]:
result = (kanto * weights).sum()
print(result)

47.4


In [12]:
climate_data = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])

In [13]:
result = np.matmul(climate_data, weights)

In [14]:
print(result)

[1.9 4.6 7.3]


In [15]:
print(climate_data @ weights)

[1.9 4.6 7.3]


## **Importing files from URLS**


In [16]:
import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x7fdbd5bb00d0>)

In [17]:
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header = 1)

In [18]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [19]:
yields = climate_data @ weights

In [20]:
print(yields)

[62.3 52.7 57.5 ... 65.3 71.6 65.8]


In [21]:
climate_results = np.concatenate((climate_data, yields.reshape(10000,1)), axis = 1)

In [22]:
climate_results

array([[25. , 76. , 99. , 62.3],
       [39. , 65. , 70. , 52.7],
       [59. , 45. , 77. , 57.5],
       ...,
       [99. , 62. , 58. , 65.3],
       [70. , 71. , 91. , 71.6],
       [92. , 39. , 76. , 65.8]])

In [23]:
np.savetxt('climate_results.txt', climate_results, fmt = '%.2f', header = 'temperature,rainfall,humidity,yield_apples',comments = '')

In [29]:
arr1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])

In [30]:
arr1 += arr1

In [31]:
print(arr1)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [32]:
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])

In [33]:
print(arr3[1,1,1])

92.0


In [36]:
print(sum(arr3[1:,0:1,2:]))

[[98. 44.]]
